version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y clang-14 clang-tidy clang-format
            apt-get install -y cmake

      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake -D CMAKE_CXX_COMPILER="/usr/bin/clang++-14" -D CMAKE_C_COMPILER="/usr/bin/clang-14" ..
            make

      - run:
          name: Run Clang-Format
          command: |
            find . -regex '.*\.\(cpp\|hpp\|c\|h\)' -exec clang-format-14 -i {} +
            git diff --exit-code || (echo "Code formatting differences found. Please run 'clang-format' on your code." && false)

      - run:
          name: Run Clang-Tidy
          command: |
            cd build
            run-clang-tidy-14 -header-filter='.*' -checks='-*,clang-analyzer-*,clang-diagnostic-*,modernize-*,performance-*,portability-*,readability-*'

      - run:
          name: Run tests
          command: |
            cd build
            ctest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
