version: 2.1

jobs:
  build:
    docker:
      - image: conanio/clang14-ubuntu16.04

    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake


      - run:
          name: Build
          command: |
            mkdir build
            cd build
            CC=clang
            CXX=clang++
            cmake ..
            make

      - run:
          name: Run tests
          command: |
            cd build
            ctest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
