version: 2.1

jobs:
  build:
    docker:
      - image: circleci/cpp:latest

    steps:
      - checkout


      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake


      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake ..
            make

      - run:
          name: Run tests
          command: |
            cd build
            ./calculator_tests  


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
