version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y clang
            sudo apt search clang
            sudo apt install -y clang-14
            sudo apt install -y cmake

      - run:
          name: Build
          command: |
            mkdir build
            cd build
            export CC=clang
            export CXX=clang++
            cmake ..
            make

      - run:
          name: Run tests
          command: |
            cd build
            ctest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
