version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y clang cmake
            
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            CC=clang
            CXX=clang++
            cmake ..
            make

      - run:
          name: Run tests
          command: |
            cd build
            ctest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
