version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: |
            # Add the LLVM repository
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
            apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"
            apt-get update
            apt-get install -y clang-14 cmake
            # Update alternatives to use Clang 14 as the default Clang version
            update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
            update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100


      - run:
          name: Build
          command: |
            mkdir build
            cd build
            CC=clang
            CXX=clang++
            cmake ..
            make

      - run:
          name: Run tests
          command: |
            cd build
            ctest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
